// app.js

document.addEventListener('DOMContentLoaded', () => {
    fetchData();
});

async function fetchData() {
    try {
        // Fetch the summary JSON generated by velocity-artifacts.js
        // Note: In a real deployment, this might be an API call. 
        // For this static dashboard, we expect the file to be relative to index.html
        // The structure is velocity-tracker-template/velocity-dashboard/index.html
        // The artifacts are in velocity-tracker-template/velocity-artifacts/velocity-summary.json

        const response = await fetch('../velocity-artifacts/velocity-summary.json');

        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }

        const data = await response.json();
        updateDashboard(data);

    } catch (error) {
        console.error('Error fetching velocity data:', error);
        // Display error state or mock data for demonstration if file not found
        // For now, let's just log it.
        alert('Could not load velocity data. Please ensure you have run "npm run velocity:report".');
    }
}

function updateDashboard(data) {
    // 1. Update Summary Cards
    const synergy = data.synergy || {};
    const latest = data.latest_run || {};
    const timeTracking = data.time_tracking || {};

    // Hours Clocked (from manual time tracking)
    const hoursClockedValue = timeTracking.actual_hours || 0;
    const hoursClocked = hoursClockedValue > 0 
        ? hoursClockedValue.toFixed(1)
        : '--';
    document.getElementById('hours-clocked').textContent = hoursClocked;

    // Estimated Solo Hours (3-4x multiplier baseline)
    const estimatedSoloHours = timeTracking.estimated_solo_hours || 
        (hoursClockedValue > 0 ? hoursClockedValue * 3.5 : 0);
    const estimatedHours = estimatedSoloHours > 0
        ? estimatedSoloHours.toFixed(1)
        : '--';
    document.getElementById('estimated-hours').textContent = estimatedHours;

    // Velocity Multiplier
    const velocityMultiplier = timeTracking.velocity_multiplier || 
        (estimatedSoloHours > 0 && hoursClockedValue > 0 
            ? estimatedSoloHours / hoursClockedValue 
            : 0);
    const multiplier = velocityMultiplier > 0
        ? velocityMultiplier.toFixed(1)
        : '--';
    document.getElementById('velocity-multiplier').textContent = multiplier;

    // Synergy Ratio
    const synergyRatio = synergy.synergy_ratio !== undefined
        ? (synergy.synergy_ratio * 100).toFixed(1) + '%'
        : '--%';
    document.getElementById('synergy-ratio').textContent = synergyRatio;

    // Regression Rate
    const regressionRate = synergy.regression_rate !== undefined
        ? (synergy.regression_rate * 100).toFixed(1) + '%'
        : '--%';
    document.getElementById('regression-rate').textContent = regressionRate;

    // Net Synergy Velocity
    const netVelocity = synergy.net_synergy_velocity !== undefined
        ? synergy.net_synergy_velocity.toFixed(2)
        : '--';
    document.getElementById('net-velocity').textContent = netVelocity;

    // 2. Update Detailed Metrics

    // Active Commit Rate (commits per actual work hour)
    const totalCommits = latest.total_commits || 0;
    const activeCommitRate = hoursClockedValue > 0
        ? (totalCommits / hoursClockedValue).toFixed(2)
        : '--';
    document.getElementById('active-commit-rate').textContent = activeCommitRate;

    // Time Saved
    const timeSaved = estimatedSoloHours > 0 && hoursClockedValue > 0
        ? (estimatedSoloHours - hoursClockedValue).toFixed(1) + ' hrs'
        : '-- hrs';
    document.getElementById('time-saved').textContent = timeSaved;

    // Efficiency Gain
    const efficiencyGain = estimatedSoloHours > 0 && hoursClockedValue > 0
        ? (((estimatedSoloHours - hoursClockedValue) / estimatedSoloHours) * 100).toFixed(1) + '%'
        : '--%';
    document.getElementById('efficiency-gain').textContent = efficiencyGain;

    // Code Survival Rate
    const codeSurvival = data.code_survival || {};
    const survivalRate = codeSurvival.survival_rate !== undefined
        ? (codeSurvival.survival_rate * 100).toFixed(1) + '%'
        : '--%';
    document.getElementById('code-survival-rate').textContent = survivalRate;

    // 3. Render Chart
    renderChart(data);
}

function renderChart(data) {
    const ctx = document.getElementById('velocityChart').getContext('2d');

    const latest = data.latest_run || {};
    const synergy = data.synergy || {};
    const timeTracking = data.time_tracking || {};

    // Get key metrics for visualization
    const hoursClockedValue = timeTracking.actual_hours || 0;
    const estimatedSoloHours = timeTracking.estimated_solo_hours || (hoursClockedValue * 3.5);
    const rawVelocity = latest.commits_per_hour || 0;
    const netVelocity = synergy.net_synergy_velocity || 0;
    const totalCommits = latest.total_commits || 0;
    const activeCommitRate = hoursClockedValue > 0 ? (totalCommits / hoursClockedValue) : 0;

    // Create a comparison chart: Actual vs Estimated Time
    new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ['Hours Worked', 'Active Commit Rate', 'Calendar Commit Rate'],
            datasets: [
                {
                    label: 'AI-Assisted (Actual)',
                    data: [hoursClockedValue, activeCommitRate, rawVelocity],
                    backgroundColor: 'rgba(34, 197, 94, 0.6)',
                    borderColor: 'rgb(34, 197, 94)',
                    borderWidth: 2
                },
                {
                    label: 'Traditional Solo Est.',
                    data: [estimatedSoloHours, activeCommitRate / 3.5, rawVelocity / 3.5],
                    backgroundColor: 'rgba(239, 68, 68, 0.6)',
                    borderColor: 'rgb(239, 68, 68)',
                    borderWidth: 2
                }
            ]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            scales: {
                y: {
                    beginAtZero: true,
                    title: {
                        display: true,
                        text: 'Value'
                    }
                }
            },
            plugins: {
                legend: {
                    display: true,
                    position: 'top'
                },
                title: {
                    display: true,
                    text: 'AI-Assisted vs Traditional Development Comparison',
                    font: {
                        size: 16
                    }
                },
                tooltip: {
                    callbacks: {
                        label: function(context) {
                            const label = context.dataset.label || '';
                            const value = context.parsed.y.toFixed(2);
                            const dataIndex = context.dataIndex;
                            
                            if (dataIndex === 0) {
                                return `${label}: ${value} hours`;
                            } else {
                                return `${label}: ${value} commits/hr`;
                            }
                        }
                    }
                }
            }
        }
    });
}
