// app.js

document.addEventListener('DOMContentLoaded', () => {
    fetchData();
});

async function fetchData() {
    try {
        // Fetch the summary JSON generated by velocity-artifacts.js
        // Note: In a real deployment, this might be an API call. 
        // For this static dashboard, we expect the file to be relative to index.html
        // The structure is velocity-tracker-template/velocity-dashboard/index.html
        // The artifacts are in velocity-tracker-template/velocity-artifacts/velocity-summary.json

        const response = await fetch('../velocity-artifacts/velocity-summary.json');

        if (!response.ok) {
            throw new Error(`HTTP error! status: ${response.status}`);
        }

        const data = await response.json();
        updateDashboard(data);

    } catch (error) {
        console.error('Error fetching velocity data:', error);
        // Display error state or mock data for demonstration if file not found
        // For now, let's just log it.
        alert('Could not load velocity data. Please ensure you have run "npm run velocity:report".');
    }
}

function updateDashboard(data) {
    // 1. Update Summary Cards
    const synergy = data.synergy || {};

    // Synergy Ratio
    const synergyRatio = synergy.synergy_ratio !== undefined
        ? (synergy.synergy_ratio * 100).toFixed(1) + '%'
        : '--%';
    document.getElementById('synergy-ratio').textContent = synergyRatio;

    // Regression Rate
    const regressionRate = synergy.regression_rate !== undefined
        ? (synergy.regression_rate * 100).toFixed(1) + '%'
        : '--%';
    document.getElementById('regression-rate').textContent = regressionRate;

    // Net Synergy Velocity
    const netVelocity = synergy.net_synergy_velocity !== undefined
        ? synergy.net_synergy_velocity.toFixed(2)
        : '--';
    document.getElementById('net-velocity').textContent = netVelocity;

    // 2. Update Detailed Metrics

    // Code Survival Rate
    const codeSurvival = data.code_survival || {};
    const survivalRate = codeSurvival.survival_rate !== undefined
        ? (codeSurvival.survival_rate * 100).toFixed(1) + '%'
        : '--%';
    document.getElementById('code-survival-rate').textContent = survivalRate;

    // 3. Render Chart
    renderChart(data);
}

function renderChart(data) {
    const ctx = document.getElementById('velocityChart').getContext('2d');

    // If we had historical data in the JSON, we would map it here.
    // The current velocity-summary.json mainly has the "latest" run and "rolling" stats.
    // Ideally, the JSON should include an array of recent runs for the chart.
    // Let's assume we might want to visualize the Rolling Average vs Latest.

    // For this MVP, let's create a simple bar chart comparing "Commits/Hour" vs "Net Synergy Velocity"

    const latest = data.latest_run || {};
    const synergy = data.synergy || {};

    const rawVelocity = latest.commits_per_hour || 0;
    const netVelocity = synergy.net_synergy_velocity || 0;

    new Chart(ctx, {
        type: 'bar',
        data: {
            labels: ['Raw Velocity', 'Net Synergy Velocity'],
            datasets: [{
                label: 'Commits per Hour',
                data: [rawVelocity, netVelocity],
                backgroundColor: [
                    'rgba(59, 130, 246, 0.5)', // Blue
                    'rgba(234, 179, 8, 0.5)'   // Yellow
                ],
                borderColor: [
                    'rgb(59, 130, 246)',
                    'rgb(234, 179, 8)'
                ],
                borderWidth: 1
            }]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            scales: {
                y: {
                    beginAtZero: true,
                    title: {
                        display: true,
                        text: 'Commits / Hour'
                    }
                }
            },
            plugins: {
                legend: {
                    display: false
                },
                title: {
                    display: true,
                    text: 'Velocity Impact Analysis'
                }
            }
        }
    });
}
